# k8s-app.yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-rest-http
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-rest-http
    spec:
      containers:
      - name: nodejs-rest-http
        image: nodejs-rest-http:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-rest-http
  labels:
    app: nodejs-rest-http
spec:
  selector:
    app: nodejs-rest-http
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30003
  type: LoadBalancer
