apiVersion: v1
kind: Template
metadata:
  name: node-slim-app
  annotations:
    iconClass: icon-jboss
    tags: nodejs, react, web app
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    description: Just building a little react app with a web builder
labels:
  application: slim-node-app
parameters:
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    value: "https://github.com/nodeshift-starters/nodejs-rest-http"
    required: true
  - name: SOURCE_REPOSITORY_REF
    description: The branch name for the application
    displayName: Source Branch
    value: master
    required: true
  - name: SOURCE_REPOSITORY_DIR
    description: The location within the source repo of the application
    displayName: Source Directory
    value: .
    required: true
  - name: OUTPUT_DIR
    description: The location of the compiled static files from your web apps builder
    displayName: Output Directory
    value: build
    required: false
  - name: GITHUB_WEBHOOK_SECRET
    description: A secret string used to configure the GitHub webhook.
    displayName: GitHub Webhook Secret
    required: true
    from: '[a-zA-Z0-9]{40}'
    generate: expression
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: node-app-builder
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: compiled-node-app-that-runs-on-slim
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: node-s2i-image
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/nodejs-12
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: node-slim-s2i
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: node:lts-alpine3.12
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: node-app-builder
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: node-app-builder:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: OUTPUT_DIR
            value: ${OUTPUT_DIR}
        from:
          kind: ImageStreamTag
          name: node-s2i-image:latest
        incremental: true
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: compiled-node-app-that-runs-on-slim
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: compiled-node-app-that-runs-on-slim:latest
    postCommit: {}
    resources: {}
    source:
      type: Dockerfile
      dockerfile: |-
      FROM node-slim-s2i:latest
      WORKDIR /usr/src/app
      COPY . .
      CMD [ "npm", "start" ]
    images:
      - from:
          kind: ImageStreamTag
          name: node-app-builder:latest
        paths:
          - sourcePath: /opt/app-root/src/node_modules
            destinationDir: .
          - sourcePath: /opt/app-root/src/package.json
            destinationDir: .
          - sourcePath: /opt/app-root/src/public
            destinationDir: .
          - sourcePath: /opt/app-root/src/app.js
            destinationDir: .
          - sourcePath: /opt/app-root/src/bin
            destinationDir: .
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: node-slim-s2i:latest
        incremental: true
      type: Docker
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: node-app-builder:latest
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: node-slim-app
    name: node-slim-app
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: node-slim-app
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: node-slim-app
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: compiled-node-app-that-runs-on-slim
          imagePullPolicy: IfNotPresent
          name: compiled-node-app-that-runs-on-slim
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
      metadata:
        labels:
          app: node-slim-app
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - compiled-node-app-that-runs-on-slim
          from:
            kind: ImageStreamTag
            name: 'compiled-node-app-that-runs-on-slim:latest'
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: node-slim-app
    name: node-slim-app
  spec:
    ports:
    - name: http
      port: 8080
    selector:
      app: node-slim-app
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: node-slim-app
    name: node-slim-app
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: node-slim-app
